services:
  db:
    image: postgres:15-alpine
    container_name: finance_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario_teste
      POSTGRES_PASSWORD: senha_secreta_teste
      POSTGRES_DB: financas
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: finance_backend_container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://usuario_teste:senha_secreta_teste@db:5432/financas?schema=public"
      PORT: 3000
      # Configuração de CORS para aceitar o frontend na porta 8080
      CORS_ORIGIN: "http://localhost:8080"

  frontend:
    build: ./frontend
    container_name: finance_frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
